### ISSUE TITLE
clone代码下来编译打包后执行报错Agent JAR loaded but agent failed to initialize

### ISSUE THREAD

**Issue by xlango** [LandGrey/copagent#7]
[INFO] Java version: 1.8
[INFO] args length: 0
[INFO] Version    : 1.3
[INFO] Build Time : 2023-09-21 16:03:52
[INFO] Found existing java process, please choose one and hit RETURN.
* [1]: 103029 spring-cloud-gateway-0.0.1-SNAPSHOT.jar
  [2]: 3903 com.intellij.idea.Main
1
[INFO] Java version: 1.8
[INFO] args length: 4
[INFO] Try to attach process 103029, please wait a moment ...
com.sun.tools.attach.AgentInitializationException: Agent JAR loaded but agent failed to initialize
        at sun.tools.attach.HotSpotVirtualMachine.loadAgent(HotSpotVirtualMachine.java:121)
        at code.landgrey.topagent.Top.attach(Top.java:162)
        at code.landgrey.topagent.Top.main(Top.java:46)
[INFO] Attach process 103029 finished .
[INFO] Result store in : /home/gomod/agent/scripts/memshell/.topagent/result.txt

**Comment by xlango** [comment]
.   ____          _            __ _ _
 /\\ / ___'_ __ _ _(_)_ __  __ _ \ \ \ \
( ( )\___ | '_ | '_| | '_ \/ _` | \ \ \ \
 \\/  ___)| |_)| | | | | || (_| |  ) ) ) )
  '  |____| .__|_| |_|_| |_\__, | / / / /
 =========|_|==============|___/=/_/_/_/
 :: Spring Boot ::                (v2.6.4)

2023-09-21 16:19:42.382  INFO 108275 --- [           main] o.v.s.SpringCloudGatewayApplication      : Starting SpringCloudGatewayApplication v0.0.1-SNAPSHOT using Java 1.8.0_382 on localhost.localdomain with PID 108275 (/home/virus/memshell/spring-cloud-gateway-0.0.1-SNAPSHOT.jar started by root in /home/virus/memshell)
2023-09-21 16:19:42.386  INFO 108275 --- [           main] o.v.s.SpringCloudGatewayApplication      : No active profile set, falling back to 1 default profile: "default"
2023-09-21 16:19:43.928  INFO 108275 --- [           main] o.s.cloud.context.scope.GenericScope     : BeanFactory id=3c3a84bf-3c7d-3fea-96b2-a97153ca95d7
2023-09-21 16:19:45.682  INFO 108275 --- [           main] o.s.cloud.commons.util.InetUtils         : Cannot determine local hostname
2023-09-21 16:19:46.445  INFO 108275 --- [           main] o.s.c.g.r.RouteDefinitionRouteLocator    : Loaded RoutePredicateFactory [After]
2023-09-21 16:19:46.445  INFO 108275 --- [           main] o.s.c.g.r.RouteDefinitionRouteLocator    : Loaded RoutePredicateFactory [Before]
2023-09-21 16:19:46.445  INFO 108275 --- [           main] o.s.c.g.r.RouteDefinitionRouteLocator    : Loaded RoutePredicateFactory [Between]
2023-09-21 16:19:46.445  INFO 108275 --- [           main] o.s.c.g.r.RouteDefinitionRouteLocator    : Loaded RoutePredicateFactory [Cookie]
2023-09-21 16:19:46.445  INFO 108275 --- [           main] o.s.c.g.r.RouteDefinitionRouteLocator    : Loaded RoutePredicateFactory [Header]
2023-09-21 16:19:46.445  INFO 108275 --- [           main] o.s.c.g.r.RouteDefinitionRouteLocator    : Loaded RoutePredicateFactory [Host]
2023-09-21 16:19:46.445  INFO 108275 --- [           main] o.s.c.g.r.RouteDefinitionRouteLocator    : Loaded RoutePredicateFactory [Method]
2023-09-21 16:19:46.446  INFO 108275 --- [           main] o.s.c.g.r.RouteDefinitionRouteLocator    : Loaded RoutePredicateFactory [Path]
2023-09-21 16:19:46.448  INFO 108275 --- [           main] o.s.c.g.r.RouteDefinitionRouteLocator    : Loaded RoutePredicateFactory [Query]
2023-09-21 16:19:46.448  INFO 108275 --- [           main] o.s.c.g.r.RouteDefinitionRouteLocator    : Loaded RoutePredicateFactory [ReadBody]
2023-09-21 16:19:46.448  INFO 108275 --- [           main] o.s.c.g.r.RouteDefinitionRouteLocator    : Loaded RoutePredicateFactory [RemoteAddr]
2023-09-21 16:19:46.448  INFO 108275 --- [           main] o.s.c.g.r.RouteDefinitionRouteLocator    : Loaded RoutePredicateFactory [Weight]
2023-09-21 16:19:46.448  INFO 108275 --- [           main] o.s.c.g.r.RouteDefinitionRouteLocator    : Loaded RoutePredicateFactory [CloudFoundryRouteService]
2023-09-21 16:19:47.673  INFO 108275 --- [           main] o.s.cloud.commons.util.InetUtils         : Cannot determine local hostname
2023-09-21 16:19:47.931  INFO 108275 --- [           main] o.s.b.a.e.web.EndpointLinksResolver      : Exposing 16 endpoint(s) beneath base path '/actuator'
2023-09-21 16:19:48.366  INFO 108275 --- [           main] o.s.b.web.embedded.netty.NettyWebServer  : Netty started on port 8080
2023-09-21 16:19:49.369  INFO 108275 --- [           main] o.s.cloud.commons.util.InetUtils         : Cannot determine local hostname
2023-09-21 16:19:50.371  INFO 108275 --- [           main] o.s.cloud.commons.util.InetUtils         : Cannot determine local hostname
2023-09-21 16:19:50.439  INFO 108275 --- [           main] o.v.s.SpringCloudGatewayApplication      : Started SpringCloudGatewayApplication in 9.625 seconds (JVM running for 10.169)

Exception in thread "Attach Listener" java.lang.reflect.InvocationTargetException
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at sun.instrument.InstrumentationImpl.loadClassAndStartAgent(InstrumentationImpl.java:386)
        at sun.instrument.InstrumentationImpl.loadClassAndCallAgentmain(InstrumentationImpl.java:411)
Caused by: java.lang.NoClassDefFoundError: org/benf/cfr/reader/api/OutputSinkFactory
        at code.landgrey.topagent.common.ClassDumpTransformer.dumpJavaIfNecessary(ClassDumpTransformer.java:62)
        at code.landgrey.topagent.utils.ClassUtils.dumpClass(ClassUtils.java:20)
        at code.landgrey.topagent.Agent.catchThief(Agent.java:98)
        at code.landgrey.topagent.Agent.agentmain(Agent.java:22)
        ... 6 more
Caused by: java.lang.ClassNotFoundException: org.benf.cfr.reader.api.OutputSinkFactory
        at java.net.URLClassLoader.findClass(URLClassLoader.java:387)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:418)
        at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:352)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:351)
        ... 10 more
Agent failed to start!

**Comment by xlango** [comment]
使用release中的cop.jar就没有问题，使用自己编译的就有问题，请问编译有什么特殊要求吗？
